### ISSUE TITLE
[EPIC] OSLC support in ASP.NET Core APIs

### ISSUE THREAD

**Issue by berezovskyi** [OSLC/oslc4net#218]
A central issue to track this stream of work.

Project: https://github.com/orgs/OSLC/projects/14/views/1

---

Now that we have a successful connection to Jazz using oslc4net client, it is time to look at OSLC server tooling. The initial work started in #25 and #9 but there are a few important items that need to be done:

- [x] We need to ensure the SDK code works under modern ASP.NET Core/MVC projects. The stock quote sample project targets a rather old ASP.NET and also is not really related to any real OSLC domain. #67 is the first issue to consider. 
- [x] We should achieve at least 1 successful integration to attain production-readiness. Worth noting that other users who forked older versions of oslc4net had success already and even added Configuration Management support (#20). A particular challenge with this task is deciding on auth. We really don't want to re-add support OAuth1.0a to oslc4net in 2024 (.NET Framework code had support for it and could not be ported to .NET 5+; RestSharp, however, does come with OAuth1.0a support and is maintained) and a solid integration with Jazz may still require it.
- [x] We should provide some primitives to build root services, service providers and a catalog, and to serve some minimally correct OSLC responses. An idea I currently have is to build a read-only OSLC CM adaptor exposing old Eclipse Lyo tickets from Eclipse Bugzilla instance using a Bugzilla XML dump I took when Eclipse announced the sunsetting of the instance.
